services:
  - type: web
    name: linktree-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      - key: DATABASE_URL
        fromDatabase:
          name: linktree-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: linktree-redis
          type: redis
          property: connectionString
      - key: JWT_SECRET
        value: hVXRLowom6ow2CwgbkAZFBn7OfU_hMXAdJIHqzp1sPuhlPNW9_9DTUDzKromIyvuyaRvu6dU6Y1_X0cO3i2ffA
      - key: JWT_REFRESH_SECRET
        value: NAqU6Eg_9LsQQTzMaULYrxqttAJrfiyZl8CnmjrFREv2TPU4333Ddm3fJJ8GWRXsaZzMcSU2BFwoTpkBW62sFw
      - key: ANALYTICS_IP_PEPPER
        value: AJg0XGPIjvdxXnJMmkzz8Ry81vOJocScnyFAoowbaik
      - key: CORS_ORIGINS
        value: https://personal-linktree-git-main-adityas-projects-383f5a26.vercel.app,https://personal-linktree-a38up182v-adityas-projects-383f5a26.vercel.app
      - key: FRONTEND_URL
        value: https://personal-linktree-git-main-adityas-projects-383f5a26.vercel.app
      - key: PUBLIC_BASE_URL
        value: https://linktree-backend-u6g7.onrender.com
      - key: COOKIE_SECURE
        value: "true"
      - key: STORAGE_BACKEND
        value: local

  - type: redis
    name: linktree-redis
    plan: free
    maxmemoryPolicy: noeviction
    ipAllowList: []

databases:
  - name: linktree-db
    plan: free
    databaseName: linkhub
    user: linkhub
